language: php

cache:
  directories:
    - $HOME/.composer/cache

install: composer install --no-interaction --prefer-source

before_script:
  - mkdir -p logs
  - sudo mkdir -p /var/qmail/bin
  - chmod +x scripts/travis.fakesendmail.sh
  - sudo cp scripts/travis.fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp scripts/travis.fakesendmail.sh /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  - wget -q https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
  - sudo chmod +x ./MailHog_linux_amd64
  - ./MailHog_linux_amd64 -smtp-bind-addr=localhost:2500 -storage=maildir -maildir-path=./logs > /dev/null 2>&1

script: ./vendor/bin/phpunit --configuration ./travis.phpunit.xml

after_script: bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
