language: php

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt update -qq
  - sudo apt install -y -qq postfix

install: composer install --no-interaction --prefer-source

before_script:
  - sudo service postfix stop
  - mkdir -p logs
  - smtp-sink -d "./logs/%d.%H.%M.%S" localhost:2500 1000 &
  - chmod +x scripts/fakesendmail.sh
  - sudo mkdir -p /var/qmail/bin
  - sudo cp scripts/fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp scripts/fakesendmail.sh /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini

script: ./vendor/bin/phpunit --configuration ./travis.phpunit.xml

after_script: bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
